### ISSUE TITLE
Victor Code Swap Discussion

### ISSUE THREAD

**Issue by evinugur** [FRCTeam1073-TheForceTeam/robot14#17]
Willie this is a good start. Here are some thoughts on the code that's been written so far.

<h4>After talking with most of the leads we reached the conclusion that this code will not be put on Atlus and the hardware will <em>not</em> be updated for WPI BattleCry unless we can get the code running on a test board (which will be built for Wednesday meeting, and have the Software working on it by Thursday's Cav Block). We simply don't have much time and this project requires mechanical updates and testing after the new hardware is put on which also is time consuming.</h4>

The test board will have the following:
- Crio and other mandatory components
- 4 Victors connected via PWM
- A jag connected via PWM with a limit on it
1. The code in `PWMMode` is 31 commits behind master. This is likely missing some competition code and will set us back down the line when we merge over stuff that uses CAN. Fetching master from the upstream will patch the changes from competition but will still present an issue with merging considering we overwrote over many large blocks of code. Since the changes should be relatively small it might just be cleaner git wise to start with a fresh branch off master and manually patch in the few blocks of code to get the robot running with the new hardware.
2. After talking with Alex today we want to still use a Jaguar for the angle adjuster because we rely on the limit switches it has. Remember the limit switch requires 0 code and we'd like to keep things that way. There's a class in wpi called Jaguar for PWM jag connections w/ out the CAN bus.
   - Additionally if any features of WPILibExtensions beyond sync groups are used we want to make sure we take these out or compensate for them.
3. The code here doesn't use Robot Builder. I'm ok with that since we're pretty much done with Atlus software-wise, but it's probably best to gather some thoughts from the other software people. Any future hardware changes will have to be reflected in the code by hand - this might be a pain down the line if we ever want to modify/improve this robot for off seasons, educational classes or demos (_like we've done with Libra for the past 2 years_)
4. After browsing through the code there's various changes to the Data Sending routine to probe for joystick information. I'm sure that code is benign, but we're so close to WPI BattleCry that we don't want to make any code changes that aren't critical.
5. There was also a change with the Ultrasonic Range Constant. I'm unsure about this.
6. Code that set error status to false was deleted. This inits to false so we're safe but we should all avoid changing things that might have side effects in the future.

**Comment by Willster419** [comment]
So would it be easier to make a new branch now and re-enter some of the changes, or try to merge all the upstream changes not related to CAN?

**Comment by evinugur** [comment]
It will be easier if we make a new branch from the latest master and work
from there.
I think we should do it at tonight's meeting to lower the risk of any one
person making a mistake (having 2 or 3 sets of eyes on something is nice)

I understand the CAN stuff needs to be removed from data sending, but a lot
of other modifications to DataSending were made that do not pertain to this
hardware swap at all. Tonight we only should make changes that are 100%
critical to this hardware swap.

On Wed, May 7, 2014 at 6:28 AM, Willard Wider notifications@github.comwrote:

> So would it be easier to make a new branch now and re-enter some of the
> changes, or try to merge all the upstream changes not related to CAN?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/FRCTeam1073-TheForceTeam/robot14/issues/17#issuecomment-42411364
> .

## 

Evin Ugur http://evinugur.com

**Comment by jeremy97** [comment]
I'll lend a hand with that. There are a lot of important changes that we made that aren't present in Willie's code. Much of the changes with the hardware update are robot builder stuff so it shouldn't be too involved.

**Comment by evinugur** [comment]
Jeremy I just texted you to come to cav block, Willie and I have started
working.

I wrapped Victor together with WPILibExtension's Invertable to create a
SmartVictor per Mr. Cowan and Greg's request for Inversion, although
nowhere in  robot14 did we ever call Invert on a SmartCANJaguar obejct. (it
is still handy to have)

Willie and I are going to start off a fresh branch of master (with a submod
index to the new WPILibExtensions with the SmartVictor) and patch in only
the needed parts of the Victor code.

The test board has been finished by Alex too.

See you all tonight.

On Wed, May 7, 2014 at 9:09 AM, jeremy97 notifications@github.com wrote:

> I'll lend a hand with that. There are a lot of important changes that we
> made that aren't present in Willie's code. Much of the changes with the
> hardware update are robot builder stuff so it shouldn't be too involved.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/FRCTeam1073-TheForceTeam/robot14/issues/17#issuecomment-42424293
> .

## 

Evin Ugur http://evinugur.com

**Comment by evinugur** [comment]
@Willster419  can you please provide us with a status update about the bot

**Comment by Willster419** [comment]
Sure.
The robot is not back together fully; the shooter is not on. However, everything that is on the robot right now is working %100. The victors were calibrated and now work great on the robot. In high gear, we had it push against the wall for a solid 5 seconds, and nothing faulted or tripped. It is fully capable of full forward to full reverse, and strafes at more than 3ft/sec without problems. The arm Jaguar also works as intended. The code in the WPIBattlecry branch is exactly what is on the robot. The plan is that mechanical will put the shooter on Monday, and it will be ready for a full systems test by 8:00.

**Comment by evinugur** [comment]
That's great. I'll be there because of 2015 VP interviews anyway, but I'll
see you then. If everything is good we should merge the code into master
and call it a day.

In the meantime, I've added some content to our trello for the post-season
meetings.

https://trello.com/b/HWx0Nqct/1073-software

On Sun, May 11, 2014 at 12:42 PM, Willard Wider notifications@github.comwrote:

> Sure.
> The robot is not back together fully; the shooter is not on. However,
> everything that is on the robot right now is working %100. The victors were
> calibrated and now work great on the robot. In high gear, we had it push
> against the wall for a solid 5 seconds, and nothing faulted or tripped. It
> is fully capable of full forward to full reverse, and strafes at more than
> 3ft/sec without problems. The arm Jaguar also works as intended. The code
> in the WPIBattlecry branch is exactly what is on the robot. The plan is
> that mechanical will put the shooter on Monday, and it will be ready for a
> full systems test by 8:00.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/FRCTeam1073-TheForceTeam/robot14/issues/17#issuecomment-42775644
> .

## 

Evin Ugur http://evinugur.com
