### ISSUE TITLE
Bling doesn't work properly

### ISSUE THREAD

**Issue by scherian03033** [FRCTeam1073-TheForceTeam/robot14#7]
Doesn't show autonomous state progressions except for shoot. Once it has shot, it stays in rainbow explosion mode.

**Comment by scherian03033** [comment]
I think one bug is that we never set RobotStatus::AutonomousStatus to TELEOP so at the end of autonomous, it still only responds to autonomous status because and ignores shooter & launcher status. The reason there's no rainbow explosion before autonomous starts is that no task is enabled to call UpdateBling. The fix for this is to set bling's initial pattern to RainbowExplosion or have RobotStatus::RobotStatusInit() call UpdateBling - I prefer the latter. We should probably also change the AUTONOMOUS_DRIVING color to purple solid and AUTONOMOUS_WAIT to blinking as it's easier to notice a short blink than to notice a longer than usual on time. Alternately, change AUTONOMOUS_WAIT to a different color than purple so it's obvious.

**Comment by scherian03033** [comment]
I have made the necessary code changes and will test them ASAP tomorrow. If they work, I'll push them at that time.

**Comment by evinugur** [comment]
I made most of them tonight and tested actually
